# Generated by Django 5.2.7 on 2025-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parameter Snapshot',
                'verbose_name_plural': 'Parameter Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('yaw', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_current', models.FloatField(blank=True, null=True)),
                ('battery_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telemetry Log',
                'verbose_name_plural': 'Telemetry Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='wf_telemetr_timesta_302f0a_idx')],
            },
        ),
    ]
